.PHONY: init set-git-config install build start test lint
.SILENT: init set-git-config install build start test lint
.ONESHELL:  # run all commands in a single shell, ensuring it runs within a local virtual env
SHELL := /bin/bash
COMMIT_MSG ?= saving work  # Only used for git push, not for creating a PR since PR commit messages will be multiline and generated by commiting.

init:
	$(MAKE) set-git-config
	pre-commit install
	# Only run GitHub CLI login if not already authenticated
	if gh auth status >/dev/null 2>&1; then \
		echo "GitHub CLI already authenticated"; \
	else \
		echo "GitHub CLI not authenticated; starting gh auth login"; \
		gh auth login; \
	fi

set-git-config:
	@git config --global --add safe.directory "$$(pwd)"
	# Attempt to discover a host gitconfig (common mount points inside containers / codespaces)
	HOST_GITCONFIG=""
	for p in /workspace/.gitconfig /workspaces/.gitconfig /home/codespace/.gitconfig /home/*/.gitconfig /root/.host_gitconfig /root/.gitconfig; do \
		[ -f "$$p" ] && HOST_GITCONFIG="$$p" && break; \
	done; \
	if [ -n "$$HOST_GITCONFIG" ]; then \
		echo "Found candidate host gitconfig at $$HOST_GITCONFIG"; \
		# cat $$HOST_GITCONFIG
		HOST_EMAIL=$$(git config --file $$HOST_GITCONFIG user.email); \
		HOST_NAME=$$(git config --file $$HOST_GITCONFIG user.name); \
	else \
		HOST_EMAIL=""; HOST_NAME=""; \
	fi; \
	if [ -n "$$HOST_EMAIL" ] && [ -n "$$HOST_NAME" ]; then \
		echo "Detected host Git identity: $$HOST_NAME $$HOST_EMAIL"; \
		read -p "Use this identity inside the container? [Y/n]: " accept; \
		# Detects Y/y/Enter response from user
		if [ -z "$$accept" ] || echo "$$accept" | grep -qi '^y'; then \
			git config --global user.email "$$HOST_EMAIL"; \
			git config --global user.name "$$HOST_NAME"; \
			echo "Git user email has been set to: $$HOST_EMAIL"; \
			echo "Git user name has been set to: $$HOST_NAME"; \
			exit 0; \
		fi; \
	fi; \
	echo "Please enter your email for Git configuration: "; \
	read email; \
	git config --global user.email "$$email"; \
	setEmail=$$(git config --global user.email); \
	echo "Git user email has been set to: $$setEmail"; \
	echo "Please enter your name for Git configuration: "; \
	read name; \
	git config --global user.name "$$name"; \
	setName=$$(git config --global user.name); \
	echo "Git user name has been set to: $$setName"

install:
	npm install

build:
ifeq ($(ENV), ci)
	npm run build -- --configuration production
else
	npm run build
endif

start:
	npm run start

test:
ifeq ($(ENV), ci)
	npm run test -- --browsers ChromeHeadlessNoSandbox --watch false
else
	npm run test
endif

lint:
	npm run lint
